// <auto-generated />
using System;
using InternetVotingApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternetVotingApplication.Migrations
{
    [DbContext(typeof(InternetVotingContext))]
    partial class InternetVotingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InternetVotingApplication.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdUzytkownik")
                        .HasColumnType("int")
                        .HasColumnName("id_uzytkownik");

                    b.HasKey("Id");

                    b.HasIndex("IdUzytkownik");

                    b.ToTable("Administrator");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.DataWyborow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("datetime")
                        .HasColumnName("dataRozpoczecia");

                    b.Property<DateTime>("DataZakonczenia")
                        .HasColumnType("datetime")
                        .HasColumnName("dataZakonczenia");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("opis");

                    b.HasKey("Id");

                    b.ToTable("DataWyborow");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.GlosowanieWyborcze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Glos")
                        .HasColumnType("bit")
                        .HasColumnName("glos");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("hash");

                    b.Property<int>("IdKandydat")
                        .HasColumnType("int")
                        .HasColumnName("id_kandydat");

                    b.Property<int?>("IdPoprzednie")
                        .HasColumnType("int")
                        .HasColumnName("id_poprzednie");

                    b.Property<int>("IdWybory")
                        .HasColumnType("int")
                        .HasColumnName("id_wybory");

                    b.HasKey("Id");

                    b.HasIndex("IdKandydat");

                    b.HasIndex("IdWybory");

                    b.ToTable("GlosowanieWyborcze");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.GlosUzytkownika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Glos")
                        .HasColumnType("bit")
                        .HasColumnName("glos");

                    b.Property<int>("IdUzytkownik")
                        .HasColumnType("int")
                        .HasColumnName("id_uzytkownik");

                    b.Property<int>("IdWybory")
                        .HasColumnType("int")
                        .HasColumnName("id_wybory");

                    b.HasKey("Id");

                    b.HasIndex("IdUzytkownik");

                    b.HasIndex("IdWybory");

                    b.ToTable("GlosUzytkownika");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Kandydat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IdWybory")
                        .HasColumnType("int")
                        .HasColumnName("id_wybory");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nazwisko");

                    b.HasKey("Id");

                    b.HasIndex("IdWybory");

                    b.ToTable("Kandydat");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("date")
                        .HasColumnName("dataUrodzenia");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(89)
                        .IsUnicode(false)
                        .HasColumnType("varchar(89)")
                        .HasColumnName("email");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("haslo");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("imie");

                    b.Property<int?>("JestAktywne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("jestAktywne")
                        .HasDefaultValueSql("((1))");

                    b.Property<Guid>("KodAktywacyjny")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kodAktywacyjny");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .HasColumnName("pesel")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Uzytkownik");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Administrator", b =>
                {
                    b.HasOne("InternetVotingApplication.Models.Uzytkownik", "IdUzytkownikNavigation")
                        .WithMany("Administrators")
                        .HasForeignKey("IdUzytkownik")
                        .IsRequired()
                        .HasConstraintName("FK_Administrator_Uzytkownik");

                    b.Navigation("IdUzytkownikNavigation");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.GlosowanieWyborcze", b =>
                {
                    b.HasOne("InternetVotingApplication.Models.Kandydat", "IdKandydatNavigation")
                        .WithMany("GlosowanieWyborczes")
                        .HasForeignKey("IdKandydat")
                        .IsRequired()
                        .HasConstraintName("FK_GlosowanieWyborcze_Kandydat");

                    b.HasOne("InternetVotingApplication.Models.DataWyborow", "IdWyboryNavigation")
                        .WithMany("GlosowanieWyborczes")
                        .HasForeignKey("IdWybory")
                        .IsRequired()
                        .HasConstraintName("FK_GlosowanieWyborcze_DataWyborow");

                    b.Navigation("IdKandydatNavigation");

                    b.Navigation("IdWyboryNavigation");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.GlosUzytkownika", b =>
                {
                    b.HasOne("InternetVotingApplication.Models.Uzytkownik", "IdUzytkownikNavigation")
                        .WithMany("GlosUzytkownikas")
                        .HasForeignKey("IdUzytkownik")
                        .IsRequired()
                        .HasConstraintName("FK_GlosUzytkownika_Uzytkownik");

                    b.HasOne("InternetVotingApplication.Models.DataWyborow", "IdWyboryNavigation")
                        .WithMany("GlosUzytkownikas")
                        .HasForeignKey("IdWybory")
                        .IsRequired()
                        .HasConstraintName("FK_GlosUzytkownika_Wybory");

                    b.Navigation("IdUzytkownikNavigation");

                    b.Navigation("IdWyboryNavigation");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Kandydat", b =>
                {
                    b.HasOne("InternetVotingApplication.Models.DataWyborow", "IdWyboryNavigation")
                        .WithMany("Kandydats")
                        .HasForeignKey("IdWybory")
                        .IsRequired()
                        .HasConstraintName("FK_Kandydat_DataWyborow");

                    b.Navigation("IdWyboryNavigation");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.DataWyborow", b =>
                {
                    b.Navigation("GlosUzytkownikas");

                    b.Navigation("GlosowanieWyborczes");

                    b.Navigation("Kandydats");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Kandydat", b =>
                {
                    b.Navigation("GlosowanieWyborczes");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Uzytkownik", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("GlosUzytkownikas");
                });
#pragma warning restore 612, 618
        }
    }
}
