// <auto-generated />
using System;
using InternetVotingApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternetVotingApplication.Migrations
{
    [DbContext(typeof(InternetVotingContext))]
    partial class InternetVotingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternetVotingApplication.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdUzytkownik")
                        .HasColumnType("int")
                        .HasColumnName("id_uzytkownik");

                    b.HasKey("Id");

                    b.HasIndex("IdUzytkownik")
                        .IsUnique();

                    b.ToTable("Administrator");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.DataWyborow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRozpoczecia")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataRozpoczecia");

                    b.Property<DateTime>("DataZakonczenia")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataZakonczenia");

                    b.Property<string>("HashGlowy")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .HasColumnName("hashGlowy")
                        .IsFixedLength();

                    b.Property<int>("LiczbaBlokow")
                        .HasColumnType("int")
                        .HasColumnName("liczbaBlokow");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("opis");

                    b.Property<int>("Wersja")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("wersja");

                    b.HasKey("Id");

                    b.HasIndex("Opis")
                        .IsUnique();

                    b.ToTable("DataWyborow");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.DziennikAudytu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Akcja")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("akcja");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("data");

                    b.Property<int?>("IdUzytkownik")
                        .HasColumnType("int")
                        .HasColumnName("id_uzytkownik");

                    b.Property<string>("Szczegoly")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("szczegoly");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.ToTable("DziennikAudytu");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.GlosUzytkownika", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataOddania")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataOddania");

                    b.Property<int>("IdUzytkownik")
                        .HasColumnType("int")
                        .HasColumnName("id_uzytkownik");

                    b.Property<int>("IdWybory")
                        .HasColumnType("int")
                        .HasColumnName("id_wybory");

                    b.HasKey("Id");

                    b.HasIndex("IdWybory");

                    b.HasIndex("IdUzytkownik", "IdWybory")
                        .IsUnique();

                    b.ToTable("GlosUzytkownika");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.GlosowanieWyborcze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .HasColumnName("hash")
                        .IsFixedLength();

                    b.Property<int>("IdKandydat")
                        .HasColumnType("int")
                        .HasColumnName("id_kandydat");

                    b.Property<string>("IdKlucza")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("idKlucza");

                    b.Property<int?>("IdPoprzednie")
                        .HasColumnType("int")
                        .HasColumnName("id_poprzednie");

                    b.Property<int>("IdWybory")
                        .HasColumnType("int")
                        .HasColumnName("id_wybory");

                    b.Property<int>("Indeks")
                        .HasColumnType("int")
                        .HasColumnName("indeks");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("char(32)")
                        .HasColumnName("nonce")
                        .IsFixedLength();

                    b.Property<string>("Podpis")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("podpis");

                    b.Property<DateTime>("ZnacznikCzasu")
                        .HasColumnType("datetime2")
                        .HasColumnName("znacznikCzasu");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.HasIndex("IdKandydat");

                    b.HasIndex("IdWybory", "Indeks")
                        .IsUnique();

                    b.ToTable("GlosowanieWyborcze");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Kandydat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdWybory")
                        .HasColumnType("int")
                        .HasColumnName("id_wybory");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("imie");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nazwisko");

                    b.HasKey("Id");

                    b.HasIndex("IdWybory", "Imie", "Nazwisko")
                        .IsUnique();

                    b.ToTable("Kandydat");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.KotwicaLancucha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("data");

                    b.Property<string>("HashGlowy")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .HasColumnName("hashGlowy")
                        .IsFixedLength();

                    b.Property<int>("IdWybory")
                        .HasColumnType("int")
                        .HasColumnName("id_wybory");

                    b.Property<int>("LiczbaBlokow")
                        .HasColumnType("int")
                        .HasColumnName("liczbaBlokow");

                    b.Property<string>("Odbiorcy")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("odbiorcy");

                    b.Property<string>("Podpis")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("podpis");

                    b.Property<string>("Powod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("powod");

                    b.HasKey("Id");

                    b.HasIndex("IdWybory", "Data");

                    b.ToTable("KotwicaLancucha");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2")
                        .HasColumnName("dataRejestracji");

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("date")
                        .HasColumnName("dataUrodzenia");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("haslo");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("imie");

                    b.Property<bool>("JestAktywne")
                        .HasColumnType("bit")
                        .HasColumnName("jestAktywne");

                    b.Property<Guid?>("KodAktywacyjny")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("kodAktywacyjny");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nazwisko");

                    b.Property<int>("NieudaneLogowania")
                        .HasColumnType("int")
                        .HasColumnName("nieudaneLogowania");

                    b.Property<string>("Pesel")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("char(11)")
                        .HasColumnName("pesel")
                        .IsFixedLength();

                    b.Property<Guid?>("TokenResetuHasla")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tokenResetuHasla");

                    b.Property<DateTime?>("TokenResetuWygasa")
                        .HasColumnType("datetime2")
                        .HasColumnName("tokenResetuWygasa");

                    b.Property<DateTime?>("ZablokowaneDo")
                        .HasColumnType("datetime2")
                        .HasColumnName("zablokowaneDo");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("KodAktywacyjny");

                    b.HasIndex("Pesel")
                        .IsUnique();

                    b.HasIndex("TokenResetuHasla");

                    b.ToTable("Uzytkownik");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.WeryfikacjaLancucha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("data");

                    b.Property<string>("HashGlowy")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .HasColumnName("hashGlowy")
                        .IsFixedLength();

                    b.Property<int>("IdWybory")
                        .HasColumnType("int")
                        .HasColumnName("id_wybory");

                    b.Property<int>("LiczbaBlokow")
                        .HasColumnType("int")
                        .HasColumnName("liczbaBlokow");

                    b.Property<bool>("Poprawny")
                        .HasColumnType("bit")
                        .HasColumnName("poprawny");

                    b.Property<string>("Szczegoly")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("szczegoly");

                    b.Property<string>("Wyzwalacz")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("wyzwalacz");

                    b.HasKey("Id");

                    b.HasIndex("IdWybory", "Data");

                    b.ToTable("WeryfikacjaLancucha");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.WiadomoscEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("NastepnaProba")
                        .HasColumnType("datetime2")
                        .HasColumnName("nastepnaProba");

                    b.Property<string>("Odbiorca")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("odbiorca");

                    b.Property<string>("OstatniBlad")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("ostatniBlad");

                    b.Property<int>("Proby")
                        .HasColumnType("int")
                        .HasColumnName("proby");

                    b.Property<string>("Temat")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("temat");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tresc");

                    b.Property<DateTime>("Utworzono")
                        .HasColumnType("datetime2")
                        .HasColumnName("utworzono");

                    b.Property<DateTime?>("Wyslano")
                        .HasColumnType("datetime2")
                        .HasColumnName("wyslano");

                    b.HasKey("Id");

                    b.HasIndex("Wyslano", "NastepnaProba");

                    b.ToTable("WiadomoscEmail");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Administrator", b =>
                {
                    b.HasOne("InternetVotingApplication.Models.Uzytkownik", "IdUzytkownikNavigation")
                        .WithMany("Administrators")
                        .HasForeignKey("IdUzytkownik")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Administrator_Uzytkownik");

                    b.Navigation("IdUzytkownikNavigation");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.GlosUzytkownika", b =>
                {
                    b.HasOne("InternetVotingApplication.Models.Uzytkownik", "IdUzytkownikNavigation")
                        .WithMany("GlosUzytkownikas")
                        .HasForeignKey("IdUzytkownik")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GlosUzytkownika_Uzytkownik");

                    b.HasOne("InternetVotingApplication.Models.DataWyborow", "IdWyboryNavigation")
                        .WithMany("GlosUzytkownikas")
                        .HasForeignKey("IdWybory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GlosUzytkownika_Wybory");

                    b.Navigation("IdUzytkownikNavigation");

                    b.Navigation("IdWyboryNavigation");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.GlosowanieWyborcze", b =>
                {
                    b.HasOne("InternetVotingApplication.Models.Kandydat", "IdKandydatNavigation")
                        .WithMany("GlosowanieWyborczes")
                        .HasForeignKey("IdKandydat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GlosowanieWyborcze_Kandydat");

                    b.HasOne("InternetVotingApplication.Models.DataWyborow", "IdWyboryNavigation")
                        .WithMany("GlosowanieWyborczes")
                        .HasForeignKey("IdWybory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_GlosowanieWyborcze_DataWyborow");

                    b.Navigation("IdKandydatNavigation");

                    b.Navigation("IdWyboryNavigation");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Kandydat", b =>
                {
                    b.HasOne("InternetVotingApplication.Models.DataWyborow", "IdWyboryNavigation")
                        .WithMany("Kandydats")
                        .HasForeignKey("IdWybory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Kandydat_DataWyborow");

                    b.Navigation("IdWyboryNavigation");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.KotwicaLancucha", b =>
                {
                    b.HasOne("InternetVotingApplication.Models.DataWyborow", "IdWyboryNavigation")
                        .WithMany("Kotwice")
                        .HasForeignKey("IdWybory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_KotwicaLancucha_DataWyborow");

                    b.Navigation("IdWyboryNavigation");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.WeryfikacjaLancucha", b =>
                {
                    b.HasOne("InternetVotingApplication.Models.DataWyborow", "IdWyboryNavigation")
                        .WithMany("Weryfikacje")
                        .HasForeignKey("IdWybory")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_WeryfikacjaLancucha_DataWyborow");

                    b.Navigation("IdWyboryNavigation");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.DataWyborow", b =>
                {
                    b.Navigation("GlosUzytkownikas");

                    b.Navigation("GlosowanieWyborczes");

                    b.Navigation("Kandydats");

                    b.Navigation("Kotwice");

                    b.Navigation("Weryfikacje");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Kandydat", b =>
                {
                    b.Navigation("GlosowanieWyborczes");
                });

            modelBuilder.Entity("InternetVotingApplication.Models.Uzytkownik", b =>
                {
                    b.Navigation("Administrators");

                    b.Navigation("GlosUzytkownikas");
                });
#pragma warning restore 612, 618
        }
    }
}
